### ISSUE TITLE
sumoLogic.logger.js does not push error message to onError callback

### ISSUE THREAD

**Issue by jamesaspence** [SumoLogic/js-sumo-logger#38]
Title says it all - when onError is called, no parameter is specified.

On the class-based version, we're specifying the error's message, but we should be passing the error object to both.

**Comment by clementallen** [comment]
I would recommend that the cross-platform class based library is used instead of the old web only version.  I do agree that it would be better to pass the error object instead of just the the message in sumoLogger.js.  Do you fancy making this change? 😃

**Comment by jamesaspence** [comment]
I'm on it! Have a fork up and everything :) quick question, I shouldn't have to do any building before running my tests, right? I made a change and am not seeing my updated tests pass - it's almost as if the old version of the code is running instead.

**Comment by clementallen** [comment]
@jamesaspence you shouldn't have to bulid anything while running tests as it pulls in the sumoLogger from the src folder

**Comment by billsaysthis** [comment]
Thanks to both of you for jumping on this. @jamesaspence, @clementallen is correct in that you should use the server-side (class-based) version of the library for security reasons, which is described in the README. If you use this in client code there's a possibility of publicizing your HTTP endpoint and having some malicious person sending traffic to it.

**Comment by jamesaspence** [comment]
Hi @billsaysthis , thanks for following up! In our case we are sending client-side logs and therefore have no choice but to use the browser-side lib (without increasing the server load to an unmanageable level).

The last time I touched this I was unable to get my updated code to pass tests and reflect the change I had made, but I will attempt to follow up later this week and troubleshoot my issues.

**Comment by clementallen** [comment]
@jamesaspence the class based implementation works just fine on client-side so I would recommend using that if you can.  I am keen to phase out the older client-side only version as there's no need to have two versions these days.

**Comment by jamesaspence** [comment]
Sounds good! This is definitely something I will be suggesting our team to push towards 😄

**Comment by billsaysthis** [comment]
Per this discussion, going to close this issue tomorrow unless I hear otherwise.

**Comment by jamesaspence** [comment]
Hi guys - adding to this, I figured out why my test was failing. I'm getting an error in the test, before the expected error. Stacktrace is as follows:

```
TypeError: Cannot read property 'then' of undefined
    at SumoLogger.sendLogs (/Users/jamesspence/projects/personal/js-sumo-logger/src/sumoLogger.js:2:3848)
    at SumoLogger.log (/Users/jamesspence/projects/personal/js-sumo-logger/src/sumoLogger.js:4:3871)
    at Context.it (/Users/jamesspence/projects/personal/js-sumo-logger/test/sumoLogger.test.js:307:20)
    at callFn (/Users/jamesspence/projects/personal/js-sumo-logger/node_modules/mocha/lib/runnable.js:372:21)
    at Test.Runnable.run (/Users/jamesspence/projects/personal/js-sumo-logger/node_modules/mocha/lib/runnable.js:364:7)
    at Runner.runTest (/Users/jamesspence/projects/personal/js-sumo-logger/node_modules/mocha/lib/runner.js:455:10)
    at /Users/jamesspence/projects/personal/js-sumo-logger/node_modules/mocha/lib/runner.js:573:12
    at next (/Users/jamesspence/projects/personal/js-sumo-logger/node_modules/mocha/lib/runner.js:369:14)
    at /Users/jamesspence/projects/personal/js-sumo-logger/node_modules/mocha/lib/runner.js:379:7
    at next (/Users/jamesspence/projects/personal/js-sumo-logger/node_modules/mocha/lib/runner.js:303:14)
    at Immediate._onImmediate (/Users/jamesspence/projects/personal/js-sumo-logger/node_modules/mocha/lib/runner.js:347:5)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

I'm looking into it now, but wondered if you guys had seen this before. I'm just doing `npm run test` after `npm i --no-shrinkwrap`, and have made very few changes (other than changing `onError` to pass entire exception object).

Using node 9.4.0 as well - I tried a different version of node (8.x) and had a similar issue. It appears to be an issue with `axios.post` returning undefined.

**Comment by jamesaspence** [comment]
agh, nvm, I'm dumb - misreading the code. Still working, and chugging along!

**Comment by jamesaspence** [comment]
Resolved the unexpected exception I was receiving in the test, have a PR here - https://github.com/SumoLogic/js-sumo-logger/pull/39

Thanks guys!
